### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by dpolivaev** [mtayseer/infoq-downloader#20]
C:\Users\Dimitry\Downloads>infoq_downloader.exe http://www.infoq.com/presentations/responsive-design
Downloading HTML file
Traceback (most recent call last):
  File "<string>", line 35, in <module>
IndexError: list index out of range

**Comment by ashishnegi** [comment]
+1 i also see this.

**Comment by yoghi** [comment]
+1

**Comment by candeira** [comment]
+1 with this presentation: http://www.infoq.com/presentations/archaeopteryx-bowkett

**Comment by philsquared** [comment]
+1 (not sure if exactly the same):

```
$ python infoq_downloader.py http://www.infoq.com/presentations/Value-Identity-State-Rich-Hickey
Downloading HTML file
Traceback (most recent call last):
  File "infoq_downloader.py", line 51, in <module>
    video_url = html_doc.cssselect('video > source')[0].attrib['src']
IndexError: list index out of range
```

**Comment by philsquared** [comment]
Oh, actually I see it's covered here: https://github.com/mtayseer/infoq-downloader/issues/9
