### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by crazy4groovy** [mtayseer/infoq-downloader#28]
```
C:\Users\Bob\Downloads>infoq_downloader.exe http://www.infoq.com/presentations/testng-groovy-spock

Downloading HTML file
Traceback (most recent call last):
  File "<string>", line 35, in <module>
IndexError: list index out of range
```

**Comment by picaron** [comment]
I get the same error

**Comment by lamby** [comment]
Same for `https://www.infoq.com/presentations/broken-performance-tools`

**Comment by ajs6f** [comment]
Same for https://www.infoq.com/presentations/category-theory-propositions-principle

**Comment by crazy4groovy** [comment]
I recommend youtube-dl, in the meantime.

**Comment by picaron** [comment]
@crazy4groovy most conferences videos on InfoQ are not available on youtube ... hence the interest for this infoq-downloader ...

**Comment by crazy4groovy** [comment]
Check out youtube-dl [supported sites](https://rg3.github.io/youtube-dl/supportedsites.html), you can find it listed there. I've tried it, and it works fab.

**Comment by picaron** [comment]
Oh thats good to know, thanks for the info

**Comment by invasionofsmallcubes** [comment]
@crazy4groovy hi, yes it downloads videos, but without the presentation it's quite useless. Is there maybe a way to download also the timed slides?

**Comment by crazy4groovy** [comment]
@invasionofsmallcubes It depends on the video how useful youtube-dl is, I suppose. I haven't found a way to download the slides as well..

**Comment by rushiagr** [comment]
Same error but different stacktrace. Note that I'm using Python3 (and pip3 to install dependencies)

```
~/src/infoq-downloader$ python3 infoq_downloader.py https://www.infoq.com/presentations/Simple-Made-Easy
Downloading HTML file
Traceback (most recent call last):
  File "infoq_downloader.py", line 51, in <module>
    video_url = html_doc.cssselect('video > source')[0].attrib['src']
IndexError: list index out of range
```
