### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by marcio-azevedo** [mtayseer/infoq-downloader#29]
Hi,

I'm getting an error when attempting to download a presentation (@Windows):
`C:\Users\me\Desktop>infoq_downloader.exe https://www.infoq.com/presentations/panel-business-data-science`

`Downloading HTML file Traceback (most recent call last): File "<string>", line 32, in <module>`
`File "F:\tayseer\projects\infoq-downloader-player\build\infoq_downloader\out00-PYZ.pyz\requests.api", line 55, in get`
`File "F:\tayseer\projects\infoq-downloader-player\build\infoq_downloader\out00-PYZ.pyz\requests.api", line 44, in request`
`File "F:\tayseer\projects\infoq-downloader-player\build\infoq_downloader\out00-PYZ.pyz\requests.sessions", line 354, in request`
`File "F:\tayseer\projects\infoq-downloader-player\build\infoq_downloader\out00-PYZ.pyz\requests.sessions", line 460, in send`
`File "F:\tayseer\projects\infoq-downloader-player\build\infoq_downloader\out00-PYZ.pyz\requests.adapters", line 250, in send`
`requests.exceptions.SSLError: [Errno 185090050] _ssl.c:343: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib`

![infoq_downloader-error](https://cloud.githubusercontent.com/assets/6273264/19346445/39ae5338-913b-11e6-85e9-7584ef575074.png)

**Comment by frozenspider** [comment]
Same for me
